### PR TITLE
Docs fixes found in UBports Live Porting

### PR DESCRIPTION
**Pull request by UniversalSuperBox**
During the [UBports live porting session](https://www.youtube.com/watch?v=nShXVDXM50A), we found some places where the documentation needed some cleaning. This PR

* Lints the kernel build errors file
* Adds the build errors we hit while building for the Fairphone 2
* Fixes some small errors in the "First steps" file

### CODE REVIEW

File: porting/common-system-build-errors.rst [hunk 1]
```diff
@@ -41,8 +41,7 @@ Flex locale error
    flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
    Aborted (core dumped)
 
+This seems to be a problem with locales and the prebuilt ``flex``. You can avoid this by using the flex installed on your host::
 
-
-Seems to be a problem with locales and the prebuilt `flex`. You can avoid this by using the "C" locale while building::
-
-   LANG=C make systemimage
+    export USE_HOST_LEX=yes
```
Comment (Herrie82) [inline porting/common-system-build-errors.rst]: Not sure what's the best approach here. LineageOS seems like it might use LC_ALL=C instead of USE_HOST_LEX=yes. This is also what I PR-ed in https://github.com/Halium/docs/pull/130

Either way, both seem to work for me and solve my issues with 7.1 build on 18.04.

Comment (UniversalSuperBox) [reply porting/common-system-build-errors.rst]: Do *both* work, or do *either* work?

Comment (Herrie82) [reply porting/common-system-build-errors.rst]: I tried both in independently with a clean build and both worked for me.

File: porting/common-kernel-build-errors.rst [hunk 2]
```diff
@@ -51,6 +47,41 @@ Example of the error::
...
+
+'Undefined reference to pidns_operations' on Linux 3.4
+------------------------------------------------------
+
+The implementation of PID Namespacing was incomplete in the Android kernel 3.4, causing the following error::
+
+   fs/built-in.o:namespaces.c:ns_entries: error: undefined reference to 'pidns_operations'
+
+To fix this issue, apply the patch `Finish implementation of PID namespace`_
+
```
Comment (doniks) [inline porting/common-kernel-build-errors.rst]: oh, actually @UniversalSuperBox I have this error at this point https://github.com/doniks/android_kernel_google_msm/commit/cf47294ba99cbb11515521ba7dffb99c93a48d3f 
with this patch, it compiles, but then at runtime I get this error: http://paste.ubuntu.com/p/9f7N8dDwWs/ however if I alternatively use these two: https://github.com/doniks/android_kernel_google_msm/commit/4d943958ff9e788f6ea7fe745c191137047eb9b8 https://github.com/doniks/android_kernel_google_msm/commit/0525c54b9add624829df432d613a1c4cbb0d0b97 I dont get the error, but get up to UT booting and apps running (with some more patches). So, I'm not sure whether we universally want to suggest this patch. 

What do you think?

Comment (Herrie82) [reply porting/common-kernel-build-errors.rst]: @doniks: We don't have issues with 3.4 kernels on Mako, Hammerhead, Onyx, Tenderloin. We use for example https://github.com/Halium/android_kernel_lge_hammerhead/commit/bd221854de33b75db7a7fa01cb34274b62a7cbf8

**Comment by UniversalSuperBox** [comment]
I do have strong feelings on USE_HOST_LEX rather than LANG... USE_HOST_LEX (later _FLEX) has been added to the LineageOS build tree specifically to solve this problem. It is a workaround, but it is a very targeted workaround. Setting the global language to the fallback C could have other effects we don't forsee.

File: porting/common-kernel-build-errors.rst (hunk 2 above)
Comment (doniks) [reply porting/common-kernel-build-errors.rst]: that makes it five kernels against one :) ok, lets put it in

**Comment by Herrie82** [comment]
@UniversalSuperBox I'm not very familiar with C(++), I can hack a bit of code, cherry pick patches but that's about it. So I trust judgement of people who have more knowledge. I just stated both work. Most solutions I found pointed to LC_ALL=C but that doesn't mean it's the most correct or best solution. As always there are multiple roads to Rome :P

**Comment by UniversalSuperBox** [comment]
For sure, many ways to get there. Let's see if this one causes problems, change it if need be. Is that an approval @doniks?
